### ISSUE TITLE
Compatibility with Powershell 7.0.6 (LTS)

### ISSUE THREAD

**Issue by keiransteele-phocas** [Devolutions/devolutions-server#41] opened 2021-06-08 02:33 UTC
Please consider making the module backwards compatible with PS7 LTS. Right now it only works in 7.1.2. AWS Lambda is running LTS Powershell. There is an issue with the Devolutions.RemoeDesktopManager.SaveResult custom type. I'm stuck with reverse engineering the module so that I can use the rest calls in Go.

**Comment by mauricecote** [comment] 2021-06-08 12:09
Noted, we will perform tests to identify the issue that you experience with the LTS.

**Comment by AlexMartigny** [comment] 2021-06-15 14:55
Hello @keiransteele-phocas ,
I get from your comment that the issue is related to referencing the included assembly. If that's the case, your problem should now be fixed on v2021.6.0, as we removed the assembly and opted for including our enums as .NET types when the module is first imported in a session.

As for the backward compatibility with PS7, I scanned the module and couldn't find anything that would not execute on PS7. If possible, please provide more information on this subject.

Thank you for your comment and feel free to submit another issue if any more concerns arise.

**Closed by AlexMartigny** 2021-06-15 14:55 UTC

**Comment by keiransteele-phocas** [comment] 2021-06-15 19:53
I've confirmed that it's working now on 7.0.3 LTS (7.0.6 in the title is a typo), thanks.
